<?php

namespace Database\Seeders;

use App\Models\Account;
use Illuminate\Database\Seeder;

class AccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Standard Chart of Accounts (COA) for Wakaf Accounting (PSAK 112 / YWDP).
     */
    public function run(): void
    {
        $accounts = [
            // ==========================================
            // 1. ASET (ASSETS)
            // ==========================================
            [
                'code'            => '1000',
                'name'            => 'Aset',
                'account_type'    => 'asset',
                'parent_code'     => null,
                'level'           => 1,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset',
            ],
            [
                'code'            => '1100',
                'name'            => 'Aset Lancar',
                'account_type'    => 'asset',
                'parent_code'     => '1000',
                'level'           => 2,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Lancar',
            ],
            [
                'code'            => '1110',
                'name'            => 'Kas dan Setara Kas',
                'account_type'    => 'asset',
                'parent_code'     => '1100',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Lancar',
            ],
            [
                'code'            => '1111',
                'name'            => 'Kas Kecil Operasional',
                'account_type'    => 'asset',
                'parent_code'     => '1110',
                'level'           => 4,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Lancar',
            ],
            [
                'code'            => '1112',
                'name'            => 'Bank BSI - Rekening Wakaf',
                'account_type'    => 'asset',
                'parent_code'     => '1110',
                'level'           => 4,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Lancar',
            ],
            [
                'code'            => '1113',
                'name'            => 'Bank Mandiri - Rekening Donasi',
                'account_type'    => 'asset',
                'parent_code'     => '1110',
                'level'           => 4,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Lancar',
            ],
            [
                'code'            => '1114',
                'name'            => 'Bank BCA - Rekening Operasional',
                'account_type'    => 'asset',
                'parent_code'     => '1110',
                'level'           => 4,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Lancar',
            ],
            [
                'code'            => '1115',
                'name'            => 'Kas di Payment Gateway (Midtrans)',
                'account_type'    => 'asset',
                'parent_code'     => '1110',
                'level'           => 4,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Lancar',
            ],
            [
                'code'            => '1120',
                'name'            => 'Piutang & Uang Muka',
                'account_type'    => 'asset',
                'parent_code'     => '1100',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Lancar',
            ],
            [
                'code'            => '1121',
                'name'            => 'Piutang Penyaluran Manfaat',
                'account_type'    => 'asset',
                'parent_code'     => '1120',
                'level'           => 4,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Lancar',
            ],
            [
                'code'            => '1122',
                'name'            => 'Uang Muka Program & Operasional',
                'account_type'    => 'asset',
                'parent_code'     => '1120',
                'level'           => 4,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Lancar',
            ],
            [
                'code'            => '1200',
                'name'            => 'Aset Tidak Lancar (Aset Wakaf)',
                'account_type'    => 'asset',
                'parent_code'     => '1000',
                'level'           => 2,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Tidak Lancar',
            ],
            [
                'code'            => '1210',
                'name'            => 'Aset Wakaf Tidak Bergerak',
                'account_type'    => 'asset',
                'parent_code'     => '1200',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Tidak Lancar',
            ],
            [
                'code'            => '1211',
                'name'            => 'Tanah Wakaf',
                'account_type'    => 'asset',
                'parent_code'     => '1210',
                'level'           => 4,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Tidak Lancar',
            ],
            [
                'code'            => '1212',
                'name'            => 'Bangunan dan Gedung Wakaf',
                'account_type'    => 'asset',
                'parent_code'     => '1210',
                'level'           => 4,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Tidak Lancar',
            ],
            [
                'code'            => '1213',
                'name'            => 'Akumulasi Penyusutan Bangunan Wakaf',
                'account_type'    => 'asset',
                'parent_code'     => '1210',
                'level'           => 4,
                'normal_balance'  => 'credit', // Kontra-aset
                'report_category' => 'Aset Tidak Lancar',
            ],
            [
                'code'            => '1220',
                'name'            => 'Aset Wakaf Bergerak',
                'account_type'    => 'asset',
                'parent_code'     => '1200',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Tidak Lancar',
            ],
            [
                'code'            => '1221',
                'name'            => 'Kendaraan Operasional / Layanan Umat',
                'account_type'    => 'asset',
                'parent_code'     => '1220',
                'level'           => 4,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Tidak Lancar',
            ],
            [
                'code'            => '1222',
                'name'            => 'Akumulasi Penyusutan Kendaraan',
                'account_type'    => 'asset',
                'parent_code'     => '1220',
                'level'           => 4,
                'normal_balance'  => 'credit', // Kontra-aset
                'report_category' => 'Aset Tidak Lancar',
            ],
            [
                'code'            => '1223',
                'name'            => 'Mesin & Peralatan Usaha Produktif',
                'account_type'    => 'asset',
                'parent_code'     => '1220',
                'level'           => 4,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Tidak Lancar',
            ],
            [
                'code'            => '1224',
                'name'            => 'Akumulasi Penyusutan Peralatan',
                'account_type'    => 'asset',
                'parent_code'     => '1220',
                'level'           => 4,
                'normal_balance'  => 'credit', // Kontra-aset
                'report_category' => 'Aset Tidak Lancar',
            ],
            [
                'code'            => '1230',
                'name'            => 'Investasi & Logam Mulia Wakaf',
                'account_type'    => 'asset',
                'parent_code'     => '1200',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Tidak Lancar',
            ],
            [
                'code'            => '1231',
                'name'            => 'Logam Mulia (Emas Wakaf)',
                'account_type'    => 'asset',
                'parent_code'     => '1230',
                'level'           => 4,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Tidak Lancar',
            ],
            [
                'code'            => '1232',
                'name'            => 'Surat Berharga / Sukuk Wakaf (CWLS)',
                'account_type'    => 'asset',
                'parent_code'     => '1230',
                'level'           => 4,
                'normal_balance'  => 'debit',
                'report_category' => 'Aset Tidak Lancar',
            ],

            // ==========================================
            // 2. LIABILITAS (LIABILITIES)
            // ==========================================
            [
                'code'            => '2000',
                'name'            => 'Liabilitas',
                'account_type'    => 'liability',
                'parent_code'     => null,
                'level'           => 1,
                'normal_balance'  => 'credit',
                'report_category' => 'Liabilitas',
            ],
            [
                'code'            => '2100',
                'name'            => 'Liabilitas Jangka Pendek',
                'account_type'    => 'liability',
                'parent_code'     => '2000',
                'level'           => 2,
                'normal_balance'  => 'credit',
                'report_category' => 'Liabilitas Jangka Pendek',
            ],
            [
                'code'            => '2110',
                'name'            => 'Hutang Biaya Operasional',
                'account_type'    => 'liability',
                'parent_code'     => '2100',
                'level'           => 3,
                'normal_balance'  => 'credit',
                'report_category' => 'Liabilitas Jangka Pendek',
            ],
            [
                'code'            => '2120',
                'name'            => 'Hutang Penyaluran Manfaat Wakaf',
                'account_type'    => 'liability',
                'parent_code'     => '2100',
                'level'           => 3,
                'normal_balance'  => 'credit',
                'report_category' => 'Liabilitas Jangka Pendek',
            ],
            [
                'code'            => '2130',
                'name'            => 'Titipan Dana / Pendapatan Diterima di Muka',
                'account_type'    => 'liability',
                'parent_code'     => '2100',
                'level'           => 3,
                'normal_balance'  => 'credit',
                'report_category' => 'Liabilitas Jangka Pendek',
            ],

            // ==========================================
            // 3. ASET NETO (NET ASSETS / EQUITIES)
            // ==========================================
            [
                'code'            => '3000',
                'name'            => 'Aset Neto Wakaf',
                'account_type'    => 'net_asset',
                'parent_code'     => null,
                'level'           => 1,
                'normal_balance'  => 'credit',
                'report_category' => 'Aset Neto',
            ],
            [
                'code'            => '3100',
                'name'            => 'Aset Neto Terikat',
                'account_type'    => 'net_asset',
                'parent_code'     => '3000',
                'level'           => 2,
                'normal_balance'  => 'credit',
                'report_category' => 'Aset Neto Terikat',
            ],
            [
                'code'            => '3110',
                'name'            => 'Aset Neto Terikat Permanen (Pokok Wakaf Abadi)',
                'account_type'    => 'net_asset',
                'parent_code'     => '3100',
                'level'           => 3,
                'normal_balance'  => 'credit',
                'report_category' => 'Aset Neto Terikat',
            ],
            [
                'code'            => '3120',
                'name'            => 'Aset Neto Terikat Temporer (Wakaf Berjangka)',
                'account_type'    => 'net_asset',
                'parent_code'     => '3100',
                'level'           => 3,
                'normal_balance'  => 'credit',
                'report_category' => 'Aset Neto Terikat',
            ],
            [
                'code'            => '3200',
                'name'            => 'Aset Neto Tidak Terikat',
                'account_type'    => 'net_asset',
                'parent_code'     => '3000',
                'level'           => 2,
                'normal_balance'  => 'credit',
                'report_category' => 'Aset Neto Tidak Terikat',
            ],
            [
                'code'            => '3210',
                'name'            => 'Dana Operasional Nazhir',
                'account_type'    => 'net_asset',
                'parent_code'     => '3200',
                'level'           => 3,
                'normal_balance'  => 'credit',
                'report_category' => 'Aset Neto Tidak Terikat',
            ],
            [
                'code'            => '3220',
                'name'            => 'Akumulasi Surplus / Defisit Periode Lalu',
                'account_type'    => 'net_asset',
                'parent_code'     => '3200',
                'level'           => 3,
                'normal_balance'  => 'credit',
                'report_category' => 'Aset Neto Tidak Terikat',
            ],

            // ==========================================
            // 4. PENERIMAAN / PENDAPATAN (REVENUE)
            // ==========================================
            [
                'code'            => '4000',
                'name'            => 'Penerimaan',
                'account_type'    => 'revenue',
                'parent_code'     => null,
                'level'           => 1,
                'normal_balance'  => 'credit',
                'report_category' => 'Penerimaan',
            ],
            [
                'code'            => '4100',
                'name'            => 'Penerimaan Wakaf',
                'account_type'    => 'revenue',
                'parent_code'     => '4000',
                'level'           => 2,
                'normal_balance'  => 'credit',
                'report_category' => 'Penerimaan Wakaf',
            ],
            [
                'code'            => '4110',
                'name'            => 'Penerimaan Wakaf Uang - Abadi',
                'account_type'    => 'revenue',
                'parent_code'     => '4100',
                'level'           => 3,
                'normal_balance'  => 'credit',
                'report_category' => 'Penerimaan Wakaf',
            ],
            [
                'code'            => '4120',
                'name'            => 'Penerimaan Wakaf Uang - Temporer',
                'account_type'    => 'revenue',
                'parent_code'     => '4100',
                'level'           => 3,
                'normal_balance'  => 'credit',
                'report_category' => 'Penerimaan Wakaf',
            ],
            [
                'code'            => '4130',
                'name'            => 'Penerimaan Wakaf Melalui Uang',
                'account_type'    => 'revenue',
                'parent_code'     => '4100',
                'level'           => 3,
                'normal_balance'  => 'credit',
                'report_category' => 'Penerimaan Wakaf',
            ],
            [
                'code'            => '4140',
                'name'            => 'Penerimaan Wakaf Aset Non-Uang',
                'account_type'    => 'revenue',
                'parent_code'     => '4100',
                'level'           => 3,
                'normal_balance'  => 'credit',
                'report_category' => 'Penerimaan Wakaf',
            ],
            [
                'code'            => '4200',
                'name'            => 'Hasil Pengelolaan Wakaf Produktif',
                'account_type'    => 'revenue',
                'parent_code'     => '4000',
                'level'           => 2,
                'normal_balance'  => 'credit',
                'report_category' => 'Hasil Pengelolaan',
            ],
            [
                'code'            => '4210',
                'name'            => 'Bagi Hasil Usaha Produktif Yayasan',
                'account_type'    => 'revenue',
                'parent_code'     => '4200',
                'level'           => 3,
                'normal_balance'  => 'credit',
                'report_category' => 'Hasil Pengelolaan',
            ],
            [
                'code'            => '4220',
                'name'            => 'Bagi Hasil Kemitraan UMKM / Produk Mitra',
                'account_type'    => 'revenue',
                'parent_code'     => '4200',
                'level'           => 3,
                'normal_balance'  => 'credit',
                'report_category' => 'Hasil Pengelolaan',
            ],
            [
                'code'            => '4300',
                'name'            => 'Penerimaan ZIS & Non-Wakaf',
                'account_type'    => 'revenue',
                'parent_code'     => '4000',
                'level'           => 2,
                'normal_balance'  => 'credit',
                'report_category' => 'Penerimaan Lainnya',
            ],
            [
                'code'            => '4310',
                'name'            => 'Penerimaan Infaq & Sedekah Terikat',
                'account_type'    => 'revenue',
                'parent_code'     => '4300',
                'level'           => 3,
                'normal_balance'  => 'credit',
                'report_category' => 'Penerimaan Lainnya',
            ],
            [
                'code'            => '4320',
                'name'            => 'Penerimaan Donasi Operasional Nazhir',
                'account_type'    => 'revenue',
                'parent_code'     => '4300',
                'level'           => 3,
                'normal_balance'  => 'credit',
                'report_category' => 'Penerimaan Lainnya',
            ],

            // ==========================================
            // 5. BEBAN & PENYALURAN (EXPENSES)
            // ==========================================
            [
                'code'            => '5000',
                'name'            => 'Penyaluran dan Beban',
                'account_type'    => 'expense',
                'parent_code'     => null,
                'level'           => 1,
                'normal_balance'  => 'debit',
                'report_category' => 'Beban',
            ],
            [
                'code'            => '5100',
                'name'            => 'Penyaluran Manfaat Wakaf',
                'account_type'    => 'expense',
                'parent_code'     => '5000',
                'level'           => 2,
                'normal_balance'  => 'debit',
                'report_category' => 'Penyaluran Manfaat',
            ],
            [
                'code'            => '5110',
                'name'            => 'Penyaluran Program Pendidikan & Beasiswa',
                'account_type'    => 'expense',
                'parent_code'     => '5100',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Penyaluran Manfaat',
            ],
            [
                'code'            => '5120',
                'name'            => 'Penyaluran Program Sosial & Kemanusiaan',
                'account_type'    => 'expense',
                'parent_code'     => '5100',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Penyaluran Manfaat',
            ],
            [
                'code'            => '5130',
                'name'            => 'Penyaluran Program Dakwah & Keagamaan',
                'account_type'    => 'expense',
                'parent_code'     => '5100',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Penyaluran Manfaat',
            ],
            [
                'code'            => '5140',
                'name'            => 'Penyaluran Program Layanan Kesehatan',
                'account_type'    => 'expense',
                'parent_code'     => '5100',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Penyaluran Manfaat',
            ],
            [
                'code'            => '5150',
                'name'            => 'Penyaluran Program Pemberdayaan Ekonomi',
                'account_type'    => 'expense',
                'parent_code'     => '5100',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Penyaluran Manfaat',
            ],
            [
                'code'            => '5200',
                'name'            => 'Beban Pengelolaan & Hak Nazhir',
                'account_type'    => 'expense',
                'parent_code'     => '5000',
                'level'           => 2,
                'normal_balance'  => 'debit',
                'report_category' => 'Beban Nazhir',
            ],
            [
                'code'            => '5210',
                'name'            => 'Bagian Hak Nazhir atas Pengelolaan Wakaf',
                'account_type'    => 'expense',
                'parent_code'     => '5200',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Beban Nazhir',
            ],
            [
                'code'            => '5220',
                'name'            => 'Beban Pemeliharaan & Perlindungan Aset Wakaf',
                'account_type'    => 'expense',
                'parent_code'     => '5200',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Beban Nazhir',
            ],
            [
                'code'            => '5300',
                'name'            => 'Beban Operasional & Administrasi Umum',
                'account_type'    => 'expense',
                'parent_code'     => '5000',
                'level'           => 2,
                'normal_balance'  => 'debit',
                'report_category' => 'Beban Operasional',
            ],
            [
                'code'            => '5310',
                'name'            => 'Beban Gaji & Honorarium Staf Pelaksana',
                'account_type'    => 'expense',
                'parent_code'     => '5300',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Beban Operasional',
            ],
            [
                'code'            => '5320',
                'name'            => 'Beban Listrik, Air, Telepon & Internet',
                'account_type'    => 'expense',
                'parent_code'     => '5300',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Beban Operasional',
            ],
            [
                'code'            => '5330',
                'name'            => 'Beban Sosialisasi, Edukasi & Literasi Wakaf',
                'account_type'    => 'expense',
                'parent_code'     => '5300',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Beban Operasional',
            ],
            [
                'code'            => '5340',
                'name'            => 'Beban Administrasi Bank & Payment Gateway',
                'account_type'    => 'expense',
                'parent_code'     => '5300',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Beban Operasional',
            ],
            [
                'code'            => '5350',
                'name'            => 'Beban Penyusutan Aset Tetap Operasional',
                'account_type'    => 'expense',
                'parent_code'     => '5300',
                'level'           => 3,
                'normal_balance'  => 'debit',
                'report_category' => 'Beban Operasional',
            ],
        ];

        // Map to keep track of inserted codes and their auto-generated IDs
        $codeToId = [];

        foreach ($accounts as $item) {
            $parentId = null;
            if (!empty($item['parent_code']) && isset($codeToId[$item['parent_code']])) {
                $parentId = $codeToId[$item['parent_code']];
            }

            $account = Account::firstOrCreate(
                ['code' => $item['code']],
                [
                    'name'            => $item['name'],
                    'account_type'    => $item['account_type'],
                    'parent_id'       => $parentId,
                    'level'           => $item['level'],
                    'normal_balance'  => $item['normal_balance'],
                    'report_category' => $item['report_category'],
                    'is_active'       => true,
                ]
            );

            // Update parent_id if newly created or missing
            if ($parentId && $account->parent_id !== $parentId) {
                $account->update(['parent_id' => $parentId]);
            }

            $codeToId[$item['code']] = $account->id;
        }
    }
}
