import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { LandingLayout } from "@/layouts/LandingLayout";
import { PageHero } from "@/components/PageHero";
import { useLang } from "@/lib/i18n";
import { translate } from "@/lib/i18n-utils";
import http from "@/lib/http";
import { imagePlaceholder } from "@/lib/placeholder";
import { resolveStorageUrl } from "@/lib/urls";
import { mitraProductDict } from "@/components/mitra-products/MitraProductI18n";
type Product = { id: number; slug: string; nama_mitra?: string | null; title_id: string; title_en: string; images: { image: string }[] }; type Response = { data: Product[]; current_page: number; last_page: number };
export default function ProdukMitraPage() { const { locale } = useLang(); const t = (key: string) => translate(mitraProductDict, locale, key); const [items, setItems] = useState<Product[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [page, setPage] = useState(1); const [lastPage, setLastPage] = useState(1);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { let active = true; http.get<Response>('/mitra-products', { params: { page, per_page: 12 } }).then((response) => { if (!active) return; setItems(response.data.data ?? []); setLastPage(response.data.last_page ?? 1); setError(null); }).catch(() => active && setError(t('product.error'))).finally(() => active && setLoading(false)); return () => { active = false; }; }, [page, locale]); return <LandingLayout><PageHero badge={t('product.badge')} title={t('product.title')} subtitle={t('product.subtitle')} breadcrumb={[{ label: t('product.badge') }]} /><main className="bg-white py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">{error && <p className="mb-6 rounded-2xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</p>}{loading ? <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="aspect-[4/3] animate-pulse rounded-[24px] bg-slate-100" />)}</div> : items.length === 0 ? <p className="rounded-[28px] border-2 border-dashed border-slate-200 bg-slate-50 p-12 text-center text-sm font-semibold text-slate-500">{t('product.empty')}</p> : <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => { const title = locale === 'en' ? item.title_en || item.title_id : item.title_id || item.title_en; return <Link key={item.id} to={`/produk-mitra/${item.slug}`} className="group overflow-hidden rounded-[24px] border border-slate-100 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><img src={resolveStorageUrl(item.images?.[0]?.image, imagePlaceholder) ?? imagePlaceholder} alt={title} className="aspect-[4/3] w-full object-cover transition group-hover:scale-105" onError={(event) => { event.currentTarget.src = imagePlaceholder; }} /><div className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-brandGreen-600">{item.nama_mitra || t('product.badge')}</p><h2 className="mt-2 font-heading text-xl font-bold text-slate-900">{title}</h2></div></Link>; })}</div>}{!loading && lastPage > 1 && <div className="mt-10 flex justify-between text-sm font-bold text-slate-600"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="disabled:opacity-40">←</button><span>{page} / {lastPage}</span><button disabled={page >= lastPage} onClick={() => setPage((value) => value + 1)} className="disabled:opacity-40">→</button></div>}</div></main></LandingLayout>; }
