import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { LandingLayout } from "@/layouts/LandingLayout";
import { useLang } from "@/lib/i18n";
import { translate } from "@/lib/i18n-utils";
import http from "@/lib/http";
import { resolveApiBaseUrl } from "@/lib/urls";
import MitraProductGallery from "@/components/mitra-products/MitraProductGallery";
import { mitraProductDict } from "@/components/mitra-products/MitraProductI18n";
type Product = { slug: string; nama_mitra?: string | null; title_id: string; title_en: string; description_id: string; description_en: string; images: { image: string; sort_order: number }[] }; type Response = { product: Product };
export default function ProdukMitraDetailPage() { const { slug } = useParams(); const { locale } = useLang(); const t = (key: string) => translate(mitraProductDict, locale, key); const [product, setProduct] = useState<Product | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { if (!slug) return; let active = true; setLoading(true); http.get<Response>(`/mitra-products/${slug}`).then((response) => active && setProduct(response.data.product)).catch(() => active && setError(t('product.detailError'))).finally(() => active && setLoading(false)); return () => { active = false; }; }, [slug, locale]); if (loading) return <LandingLayout><div className="mx-auto max-w-6xl animate-pulse p-12 text-slate-400">Memuat produk...</div></LandingLayout>; if (!product || error) return <LandingLayout><div className="mx-auto max-w-6xl p-12"><p className="rounded-2xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error || t('product.detailError')}</p></div></LandingLayout>; const title = locale === 'en' ? product.title_en || product.title_id : product.title_id || product.title_en; const description = locale === 'en' ? product.description_en || product.description_id : product.description_id || product.description_en; return <LandingLayout><main className="bg-slate-50 py-12 sm:py-16"><div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><Link to="/produk-mitra" className="text-sm font-bold text-brandGreen-700">← {t('product.back')}</Link><div className="mt-6 grid gap-8 lg:grid-cols-[minmax(0,1fr)_360px]"><MitraProductGallery images={[...product.images].sort((a, b) => a.sort_order - b.sort_order)} title={title} /><aside className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-brandGreen-600">{product.nama_mitra || t('product.badge')}</p><h1 className="mt-3 font-heading text-3xl font-bold text-slate-900">{title}</h1><p className="mt-5 whitespace-pre-line text-sm leading-7 text-slate-600">{description}</p><a href={`${resolveApiBaseUrl()}/mitra-products/${product.slug}/contact`} target="_blank" rel="noreferrer" className="mt-8 inline-flex w-full items-center justify-center rounded-2xl bg-brandGreen-600 px-5 py-3 text-sm font-bold text-white hover:bg-brandGreen-700">{t('product.contact')}</a></aside></div></div></main></LandingLayout>; }
