import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import http from "@/lib/http";
import { useToast } from "@/components/ui/ToastProvider";
import EditorGalleryMitraFormHeader from "@/components/management/editor/gallery-mitra/form/EditorGalleryMitraFormHeader";
import EditorGalleryMitraFormMain from "@/components/management/editor/gallery-mitra/form/EditorGalleryMitraFormMain";
import EditorGalleryMitraFormSidebar from "@/components/management/editor/gallery-mitra/form/EditorGalleryMitraFormSidebar";
import { emptyGalleryMitraForm, galleryMitraFolder, type GalleryMitra, type GalleryMitraFormState } from "@/components/management/editor/gallery-mitra/GalleryMitraTypes";
const countWords = (value: string) => value.trim() ? value.trim().split(/\s+/u).length : 0;
type ApiError = { response?: { data?: { errors?: Record<string, string[]>; message?: string } } };
const getErrorMessages = (error: unknown, fallback: string) => { const payload = (error as ApiError)?.response?.data; return payload?.errors ? Object.values(payload.errors).flat().map(String) : [payload?.message ?? fallback]; };
export default function EditorGalleryMitraEditPage() { const { id } = useParams(); const galleryId = Number(id); const navigate = useNavigate(); const toast = useToast(); const [form, setForm] = useState<GalleryMitraFormState>(emptyGalleryMitraForm); const [loading, setLoading] = useState(true); const [previewUrl, setPreviewUrl] = useState<string | null>(null); const [uploading, setUploading] = useState(false); const [uploadError, setUploadError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [errors, setErrors] = useState<string[]>([]);
  useEffect(() => { let active = true; http.get<GalleryMitra>(`/editor/gallery-mitra/${galleryId}`).then((response) => { if (!active) return; const item = response.data; setForm({ image: item.image ?? '', caption_id: item.caption_id ?? '', caption_en: item.caption_en ?? '', status: (item.status as GalleryMitraFormState['status']) ?? 'draft' }); }).catch((error) => { if (active) setErrors(getErrorMessages(error, 'Gagal memuat aktivitas mitra.')); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [galleryId]);
  const onUpload = async (file: File) => { setUploadError(null); if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) { setUploadError('Format gambar harus JPG, JPEG, PNG, atau WebP.'); return; } if (file.size > 10 * 1024 * 1024) { setUploadError('Ukuran gambar maksimal 10 MB.'); return; } setUploading(true); const localUrl = URL.createObjectURL(file); if (previewUrl) URL.revokeObjectURL(previewUrl); setPreviewUrl(localUrl); try { const data = new FormData(); data.append('file', file); data.append('folder', galleryMitraFolder); const response = await http.post<{ path: string }>('/editor/uploads/image', data, { headers: { 'Content-Type': 'multipart/form-data' } }); setForm((current) => ({ ...current, image: response.data.path })); toast.success('Gambar berhasil diperbarui.', { title: 'Berhasil' }); } catch { setUploadError('Gagal mengunggah gambar.'); } finally { setUploading(false); } };
  const onSubmit = async () => { const validationErrors: string[] = []; if (!form.image) validationErrors.push('Gambar aktivitas wajib diisi.'); if (!form.caption_id.trim()) validationErrors.push('Caption Indonesia wajib diisi.'); if (!form.caption_en.trim()) validationErrors.push('Caption English wajib diisi.'); if (countWords(form.caption_id) > 3 || countWords(form.caption_en) > 3) validationErrors.push('Setiap caption maksimal 3 kata.'); if (validationErrors.length) { setErrors(validationErrors); return; } setSaving(true); setErrors([]); try { await http.put(`/editor/gallery-mitra/${galleryId}`, form); toast.success('Aktivitas mitra berhasil diperbarui.', { title: 'Berhasil' }); navigate('/editor/gallery-mitra', { replace: true }); } catch (error) { setErrors(getErrorMessages(error, 'Gagal memperbarui aktivitas mitra.')); } finally { setSaving(false); } };
  if (loading) return <div className="mx-auto w-full max-w-6xl animate-pulse rounded-[28px] border border-slate-200 bg-white p-10 text-sm font-semibold text-slate-400">Memuat aktivitas mitra...</div>;
  return <div className="mx-auto w-full max-w-6xl space-y-6 pb-20"><EditorGalleryMitraFormHeader mode="edit" saving={saving} uploading={uploading} canSubmit={!saving && !uploading} onBack={() => navigate('/editor/gallery-mitra')} onSubmit={onSubmit} />{errors.length > 0 && <div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{errors.map((error, index) => <p key={index}>{error}</p>)}</div>}<div className="grid grid-cols-1 gap-6 lg:grid-cols-12"><div className="lg:col-span-8"><EditorGalleryMitraFormMain form={form} previewUrl={previewUrl} uploading={uploading} uploadError={uploadError} disabled={saving} onUpload={onUpload} onRemove={() => { setForm((current) => ({ ...current, image: '' })); if (previewUrl) URL.revokeObjectURL(previewUrl); setPreviewUrl(null); }} /></div><div className="lg:col-span-4"><EditorGalleryMitraFormSidebar form={form} disabled={saving} onChange={(field, value) => setForm((current) => ({ ...current, [field]: value }))} /></div></div></div>; }
